 name: Build and Test

 on:
   push:
     branches:
       - main

 jobs:
   build:
     runs-on: ubuntu-latest

     steps:
       - name: Get the code
         uses: actions/checkout@v3

       - name: Build the application
         run: npm build
       - name: Run test
         run: npm test
